#--------------------------------------------------------------------------------------------------#
# Compiler Flags :: GNU
#--------------------------------------------------------------------------------------------------#
GET_FILENAME_COMPONENT (C_COMPILER_NAME ${CMAKE_C_COMPILER} NAME)
GET_FILENAME_COMPONENT (CXX_COMPILER_NAME ${CMAKE_CXX_COMPILER} NAME)
GET_FILENAME_COMPONENT (Fortran_COMPILER_NAME ${CMAKE_Fortran_COMPILER} NAME)
#--------------------------------------------------------------------------------------------------#
SET(MAIN_FILENAME_FLAG "-D__FILENAME__='\"$(subst ${CMAKE_SOURCE_DIR}/,,$(abspath $(<)))\"'")
IF (CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
  # OVERALL
  SET(MAIN_FLAGS_OVERALL "")
  SET(MAIN_FLAGS_OVERALL "${MAIN_FLAGS_OVERALL} -xf95-cpp-input")
  # MACHINE
  SET(MAIN_FLAGS_MACHINE "")
  SET(MAIN_FLAGS_MACHINE "${MAIN_FLAGS_MACHINE} -march=core-avx2")
  # OPTIMIZATION
  SET(MAIN_FLAGS_OPTIMIZATION "")
  SET(MAIN_FLAGS_OPTIMIZATION "${MAIN_FLAGS_OPTIMIZATION} -O3")
  SET(MAIN_FLAGS_OPTIMIZATION "${MAIN_FLAGS_OPTIMIZATION} -funroll-loops")
  SET(MAIN_FLAGS_OPTIMIZATION "${MAIN_FLAGS_OPTIMIZATION} -finline-functions")
  SET(MAIN_FLAGS_OPTIMIZATION "${MAIN_FLAGS_OPTIMIZATION} -finline-limit=1500")
  # COMMON CXX
  SET(MAIN_CXX_FLAGS_OVERALL "")
  SET(MAIN_CXX_FLAGS_OVERALL "${MAIN_CXX_FLAGS_OVERALL} -DGNU")
  SET(MAIN_CXX_FLAGS_OVERALL "${MAIN_CXX_FLAGS_OVERALL} -std=c++17")
  SET(MAIN_CXX_FLAGS_OVERALL "${MAIN_CXX_FLAGS_OVERALL} ${MAIN_FILENAME_FLAG}")
  # COMMON FORTRAN
  SET(MAIN_Fortran_FLAGS_OVERALL "")
  SET(MAIN_Fortran_FLAGS_OVERALL "${MAIN_Fortran_FLAGS_OVERALL} -DGNU")
  SET(MAIN_Fortran_FLAGS_OVERALL "${MAIN_Fortran_FLAGS_OVERALL} -std=gnu")
  SET(MAIN_Fortran_FLAGS_OVERALL "${MAIN_Fortran_FLAGS_OVERALL} -fbackslash")
  SET(MAIN_Fortran_FLAGS_OVERALL "${MAIN_Fortran_FLAGS_OVERALL} -fdefault-real-8")
  SET(MAIN_Fortran_FLAGS_OVERALL "${MAIN_Fortran_FLAGS_OVERALL} -fdefault-double-8")
  SET(MAIN_Fortran_FLAGS_OVERALL "${MAIN_Fortran_FLAGS_OVERALL} -ffree-line-length-none")
  SET(MAIN_Fortran_FLAGS_OVERALL "${MAIN_Fortran_FLAGS_OVERALL} ${MAIN_FILENAME_FLAG}")
  # COMMON DEBUGGING & CODE GENERATION
  SET(MAIN_FLAGS_DEBUGGING "")
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -g")
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -O2")
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -ggdb3")
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -Wall")
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -Wextra")
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -Wpedantic")
  #------------------------------------------#
  # Deactivated Warnings
  #------------------------------------------#
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -Wno-unused-function")
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -Wno-compare-reals")
  SET(MAIN_FLAGS_DEBUGGING "${MAIN_FLAGS_DEBUGGING} -Wno-unused-dummy-argument")
  #------------------------------------------#
  # DEBUGGING & CODE GENERATION - CXX
  SET(MAIN_CXX_FLAGS_DEBUGGING "")
  SET(MAIN_CXX_FLAGS_DEBUGGING "${MAIN_CXX_FLAGS_DEBUGGING} -Weffc++")
  SET(MAIN_CXX_FLAGS_DEBUGGING "${MAIN_CXX_FLAGS_DEBUGGING} -Wformat=2")
  SET(MAIN_CXX_FLAGS_DEBUGGING "${MAIN_CXX_FLAGS_DEBUGGING} -Wfloat-equal")
  # DEBUGGING & CODE GENERATION - FORTRAN
  SET(MAIN_Fortran_FLAGS_DEBUGGING "")
  SET(MAIN_Fortran_FLAGS_DEBUGGING "${MAIN_Fortran_FLAGS_DEBUGGING} -fbacktrace")
  SET(MAIN_Fortran_FLAGS_DEBUGGING "${MAIN_Fortran_FLAGS_DEBUGGING} -fcheck=bounds")
  SET(MAIN_Fortran_FLAGS_DEBUGGING "${MAIN_Fortran_FLAGS_DEBUGGING} -finit-real=snan")
  SET(MAIN_Fortran_FLAGS_DEBUGGING "${MAIN_Fortran_FLAGS_DEBUGGING} -ffpe-trap=zero")
  SET(MAIN_Fortran_FLAGS_DEBUGGING "${MAIN_Fortran_FLAGS_DEBUGGING} -ffpe-trap=invalid")
  SET(MAIN_Fortran_FLAGS_DEBUGGING "${MAIN_Fortran_FLAGS_DEBUGGING} -ffpe-trap=overflow")
  SET(MAIN_Fortran_FLAGS_DEBUGGING "${MAIN_Fortran_FLAGS_DEBUGGING} -ffpe-trap=underflow")
  
  # CMAKE COMMON FLAGS: CXX + FORTRAN
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${MAIN_CXX_FLAGS_OVERALL}")
  SET(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS}")
  SET(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} ${MAIN_Fortran_FLAGS_OVERALL}")
  # CMAKE RELEASE FLAGS: CXX + FORTRAN
  SET(CMAKE_CXX_FLAGS_RELEASE "")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${MAIN_FLAGS_OPTIMIZATION}")
  SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${MAIN_FLAGS_MACHINE}")
  SET(CMAKE_Fortran_FLAGS_RELEASE "")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} ${MAIN_FLAGS_OPTIMIZATION}")
  SET(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} ${MAIN_FLAGS_MACHINE}")
  # CMAKE PROFILE FLAGS: CXX + FORTRAN
  SET(CMAKE_CXX_FLAGS_PROFILE "")
  SET(CMAKE_CXX_FLAGS_PROFILE "${CMAKE_CXX_FLAGS_PROFILE} -pg")
  SET(CMAKE_CXX_FLAGS_PROFILE "${CMAKE_CXX_FLAGS_PROFILE} ${MAIN_FLAGS_OPTIMIZATION}")
  SET(CMAKE_CXX_FLAGS_PROFILE "${CMAKE_CXX_FLAGS_PROFILE} ${MAIN_FLAGS_MACHINE}")
  SET(CMAKE_Fortran_FLAGS_PROFILE "")
  SET(CMAKE_Fortran_FLAGS_PROFILE "${CMAKE_Fortran_FLAGS_PROFILE} -pg")
  SET(CMAKE_Fortran_FLAGS_PROFILE "${CMAKE_Fortran_FLAGS_PROFILE} ${MAIN_FLAGS_OPTIMIZATION}")
  SET(CMAKE_Fortran_FLAGS_PROFILE "${CMAKE_Fortran_FLAGS_PROFILE} ${MAIN_FLAGS_MACHINE}")
  # CMAKE DEBUG FLAGS: CXX + FORTRAN
  SET(CMAKE_CXX_FLAGS_DEBUG "")
  SET(CMAKE_CXX_FLAGS_DEBUG "${MAIN_FLAGS_DEBUGGING}")
  SET(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${MAIN_CXX_FLAGS_DEBUGGING}")
  SET(CMAKE_Fortran_FLAGS_DEBUG "")
  SET(CMAKE_Fortran_FLAGS_DEBUG "${MAIN_FLAGS_DEBUGGING}")
  SET(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} ${MAIN_Fortran_FLAGS_DEBUGGING}")
ENDIF()
#--------------------------------------------------------------------------------------------------#
